name: ppforeach
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Masashi Fujita <objectxtreme@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
#  path: ^1.4.1
  pointycastle: ^1.0.1
  typed_data: ^1.1.6
  quiver: ^2.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
